import { useState } from "react";

const moments = ["A birthday", "A festival", "A thank you", "Just because"];
const styles = ["Personal & sentimental", "Festive & abundant", "Calm & restorative", "Zodiac inspired"];

export function GiftFinder({ open, onOpen }) {
  const [moment, setMoment] = useState("");
  const [style, setStyle] = useState("");

  return <section id="gift-finder" className="bg-[#261b25] px-5 py-20 text-[#fff9ed] sm:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#edbb59]">The Mahika concierge</p><h2 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">A gift finder that feels more like a <em className="font-normal text-[#eabd67]">good intuition.</em></h2><p className="mt-5 max-w-md text-sm leading-7 text-[#f8eee2]/70">Tell us about the moment and the feeling. We will help you begin with a meaningful direction, whether it is a zodiac gift or something beautifully universal.</p><div className="mt-8 flex gap-6 text-xs font-semibold text-[#f9e1a5]"><span>01 · Pick the moment</span><span>02 · Set the mood</span></div></div><div className="rounded-[1.5rem] border border-[#f7d486]/20 bg-[#fffaf1]/8 p-6 backdrop-blur sm:p-8"><p className="text-sm font-bold">What are we celebrating?</p><div className="mt-4 grid grid-cols-2 gap-3">{moments.map((item) => <button type="button" key={item} onClick={() => { setMoment(item); onOpen(); }} className={`rounded-xl border px-4 py-4 text-left text-sm font-semibold transition ${moment === item ? "border-[#e9b74f] bg-[#e9b74f] text-[#2b1c1c]" : "border-white/15 bg-white/5 text-[#fff8eb] hover:bg-white/10"}`}>{item}</button>)}</div><p className="mt-7 text-sm font-bold">What feeling should it carry?</p><div className="mt-4 flex flex-wrap gap-2">{styles.map((item) => <button type="button" key={item} onClick={() => { setStyle(item); onOpen(); }} className={`rounded-full border px-4 py-2.5 text-xs font-bold transition ${style === item ? "border-[#e9b74f] bg-[#e9b74f] text-[#2b1c1c]" : "border-white/15 text-[#fff8eb] hover:bg-white/10"}`}>{item}</button>)}</div>{open && moment && style && <div className="mt-7 rounded-xl bg-[#f9e5ac] p-4 text-[#33211d]"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#a46132]">Your cosmic direction</p><p className="mt-1 font-serif text-xl">For {moment.toLowerCase()}, try a {style.toLowerCase()} hamper.</p><a href="#hampers" className="mt-3 inline-block text-sm font-extrabold underline underline-offset-4">See your edit →</a></div>}</div></div></section>;
}
